export const LOGO_STYLES = [
  "Minimalist",
  "Flat Geometric",
  "Vintage / Retro",
  "Mascot Character",
  "Modern Tech",
  "Futuristic Neon",
  "3D Gradient",
  "Metallic Chrome",
  "Hand-Drawn Sketch",
  "Watercolor Symbol",
  "Abstract Shapes",
  "Elegant Serif Branding",
  "Monogram Letters",
  "Badge / Emblem",
  "Line Art",
  "Pixel Art",
  "Graffiti Street Style",
  "Sports Team Mascot",
  "Luxury Gold Foil",
  "Cyberpunk",
  "Anime-Inspired",
  "Corporate Clean"
];
